### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by GuillaumePressiat** [GuillaumePressiat/pmeasyr2#1]
- [ ] **vroom** : tester les imports avec vroom pour toutes les fonctions : est-ce suffisament fiable pour le moment et l'apport est-il réel sur toutes les plate-formes ? Est-ce que la gestion des problèmes à l'import est aussi efficace qu'avec readr, et est-ce que les NA sont pris en charge de manière identique, bref quels risques de discontinuités en passant de readr à vroom ?
_pour le moment les fonctions modifiées sur ce point sont_ :

  - [x] irsa
  - [x] iano_mco (out)
  - [x] itra (mco)  

- [ ] **restructurer le code** : séparer les imports parties variables (rsa, rum, etc) des imports parties fixes uniquement (ano, med, tra, dmi), pour tous les fichiers, deviner le format et le type de fichier à partir du nom du fichier. Cela permettra d'alléger beaucoup le code, mais peut être fait indépendamment de vroom
- [ ] **formatage** : utiliser les noms des variables pour faire les opérations de formatage (MT > / 100, NOMBRE / 1000, etc), gérer les dates directement dans vroom ou readr avec locale(date = "...")
